environment:  #секция, где определяются переменные окружения для сборки
  nodejs_version: "22" # самая последняя стабильная версия

branches: # какие ветки git отслеживаются
  only:
    - master  # ветка git
    - main

cache: # кеширование, чтобы node_modules работал быстрее
  - '%LOCALAPPDATA%\npm-cache'
  - 'src\client\node_modules'
  - 'src\server\node_modules' 

install:
  - npm run install-all  # команда установки зависимостей, указанных в файле package.json и клиентской, и серверной части

build_script: #секция, в которой указаны команды для сборки проекта
  - npm ci --prefix src/client
  - npm run build-client   # команда сборки из файла package.json клиентской части

test_script: #секция, в которой указаны команды для тестирования проекта
  - npm run lint --prefix src/client # скрипт тестирования
